export GOCACHE := env_var_or_default('GOCACHE', env_var_or_default('TMPDIR', '/tmp') + '/restop-go-cache')

test:
    go fmt ./...
    git ls-files -z -- '*.go' | xargs -0 gopls check -severity=hint
    go vet ./...
    go test -race ./...
